- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  become: yes
  roles:
    - user_accounts
    - common

- name: Manage vagrant instances
  hosts: control_nodes
  connection: local
  become: no
  gather_facts: no
  roles:
    - manage_vagrant_instances

- name: Configure control node
  hosts: control_nodes
  become: yes
  roles:
    - control_node

