- name: restart ssh
  service:
    name: "{{ common_ssh_service_name }}"
    state: restarted

- name: reboot
  shell: sleep 2 && reboot
  async: 30
  poll: 0
  when: ansible_connection != "local"

- name: wait for instance
  delegate_to: localhost
  become: no
  wait_for:
    port: "{{ ansible_port }}"
    host: "{{ ansible_host }}"
    search_regex: OpenSSH
    timeout: 500
    delay: 40
